"""
Django settings for energy_monitor project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#4412682ddrg!^9@@@d)*ti4ddo6dz4*wb_!5!+mwh*g$#4e%c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'energy',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'energy_monitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'energy_monitor.wsgi.application'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# your_project_name/settings.py

# ... other settings ...

# --- Email Configuration for Sending Real Emails ---
# Change this to use the SMTP backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP Host (e.g., for Gmail)
EMAIL_HOST = 'smtp.gmail.com' # Or your email provider's SMTP host

# SMTP Port (587 for TLS, 465 for SSL)
EMAIL_PORT = 587

# Use TLS (Transport Layer Security) for secure connection
EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False # Only set one of these to True, usually TLS is preferred

# Your email address (the one Django will use to send emails from)
EMAIL_HOST_USER = 'nguthucharles02@gmail.com' # REPLACE WITH YOUR GMAIL ADDRESS

# Your email password or app-specific password
# WARNING: Storing passwords directly in settings.py is NOT secure for production.
# Use environment variables (e.g., python-decouple, os.environ) for production.
EMAIL_HOST_PASSWORD = 'msvo tbvn jlsv ahar' # REPLACE WITH YOUR GMAIL APP PASSWORD

# Default 'From' email address for outgoing emails
DEFAULT_FROM_EMAIL = 'nguthucharles02@gmail.com' # Should usually match EMAIL_HOST_USER

# --- End Email Configuration ---

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'energy',
        'USER': 'root',
        'PASSWORD':'Charles01.',
        'HOST': '127.0.0.1',
        'PORT':'3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRs = [os.path.join(BASE_DIR ,'static'),
                    ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
