# Generated by Django 5.2.3 on 2025-07-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(max_length=50)),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
