# Generated by Django 5.2.3 on 2025-07-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_person_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
    ]
